export type ScheduleItem = {
  day: string;
  time: string;
  subject: string;
  teacher: string;
  room: string;
  type: string;
  subgroup: 'ust' | 'alt' | 'hamisi';
  week: 'ust' | 'alt' | 'hamisi';
};

export const FIXED_SCHEDULE: ScheduleItem[] = [
  // I GÜN - Bazar ertəsi
  {
    day: 'Bazar ertəsi',
    time: '14:05-15:25',
    subject: 'Obyektyönlü proqramlaşdırma',
    teacher: 'Validə Nuriyeva',
    room: '311',
    type: 'məş',
    subgroup: 'hamisi',
    week: 'ust',
  },
  {
    day: 'Bazar ertəsi',
    time: '14:05-15:25',
    subject: 'Diskret riyaziyyat',
    teacher: 'Lalə Rzayeva',
    room: '303',
    type: 'məş',
    subgroup: 'hamisi',
    week: 'alt',
  },
  {
    day: 'Bazar ertəsi',
    time: '15:35-16:55',
    subject: 'Verilənlər bazası sistemləri',
    teacher: 'Rəsmiyyə Əmiraslanova',
    room: '305',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'hamisi',
  },
  {
    day: 'Bazar ertəsi',
    time: '17:05-18:25',
    subject: 'Kompüter şəbəkələri',
    teacher: 'Ceyhun Əlizadə',
    room: '308',
    type: 'lab',
    subgroup: 'ust',
    week: 'hamisi',
  },
  {
    day: 'Bazar ertəsi',
    time: '17:05-18:25',
    subject: 'Əməliyyat sistemləri',
    teacher: 'Elnur Xəlilov',
    room: '309',
    type: 'lab',
    subgroup: 'alt',
    week: 'hamisi',
  },

  // II GÜN - Çərşənbə axşamı
  {
    day: 'Çərşənbə axşamı',
    time: '12:30-13:50',
    subject: 'Diskret riyaziyyat',
    teacher: 'Lalə Rzayeva',
    room: '306',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'hamisi',
  },
  {
    day: 'Çərşənbə axşamı',
    time: '14:05-15:25',
    subject: 'Kompüter şəbəkələri',
    teacher: 'Ceyhun Əlizadə',
    room: '305',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'hamisi',
  },
  {
    day: 'Çərşənbə axşamı',
    time: '15:35-16:55',
    subject: 'Əməliyyat sistemləri',
    teacher: 'Elnur Xəlilov',
    room: '308',
    type: 'lab',
    subgroup: 'ust',
    week: 'hamisi',
  },
  {
    day: 'Çərşənbə axşamı',
    time: '15:35-16:55',
    subject: 'Kompüter şəbəkələri',
    teacher: 'Ceyhun Əlizadə',
    room: '309',
    type: 'lab',
    subgroup: 'alt',
    week: 'hamisi',
  },

  // III GÜN - Çərşənbə
  {
    day: 'Çərşənbə',
    time: '14:05-15:25',
    subject: 'Əməliyyat sistemləri',
    teacher: 'Elnur Xəlilov',
    room: '306',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'hamisi',
  },
  {
    day: 'Çərşənbə',
    time: '15:35-16:55',
    subject: 'Obyektyönlü proqramlaşdırma',
    teacher: 'Validə Nuriyeva',
    room: '306',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'hamisi',
  },
  {
    day: 'Çərşənbə',
    time: '17:05-18:25',
    subject: 'Verilənlər bazası sistemləri',
    teacher: 'Rəsmiyyə Əmiraslanova',
    room: '308',
    type: 'lab',
    subgroup: 'ust',
    week: 'ust',
  },
  {
    day: 'Çərşənbə',
    time: '17:05-18:25',
    subject: 'Obyektyönlü proqramlaşdırma',
    teacher: 'Validə Nuriyeva',
    room: '309',
    type: 'lab',
    subgroup: 'ust',
    week: 'alt',
  },
  {
    day: 'Çərşənbə',
    time: '17:05-18:25',
    subject: 'Obyektyönlü proqramlaşdırma',
    teacher: 'Validə Nuriyeva',
    room: '309',
    type: 'lab',
    subgroup: 'alt',
    week: 'ust',
  },
  {
    day: 'Çərşənbə',
    time: '17:05-18:25',
    subject: 'Verilənlər bazası sistemləri',
    teacher: 'Rəsmiyyə Əmiraslanova',
    room: '308',
    type: 'lab',
    subgroup: 'alt',
    week: 'alt',
  },

  // IV GÜN - Cümə axşamı
  {
    day: 'Cümə axşamı',
    time: '14:05-15:25',
    subject: 'Kompüter şəbəkələri',
    teacher: 'Ceyhun Əlizadə',
    room: '306',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'ust',
  },
  {
    day: 'Cümə axşamı',
    time: '14:05-15:25',
    subject: 'Verilənlər bazası sistemləri',
    teacher: 'Rəsmiyyə Əmiraslanova',
    room: '306',
    type: 'müh',
    subgroup: 'hamisi',
    week: 'alt',
  },
  {
    day: 'Cümə axşamı',
    time: '15:35-16:55',
    subject: 'Verilənlər bazası sistemləri',
    teacher: 'Rəsmiyyə Əmiraslanova',
    room: '306',
    type: 'məş',
    subgroup: 'hamisi',
    week: 'ust',
  },
  {
    day: 'Cümə axşamı',
    time: '15:35-16:55',
    subject: 'Kompüter şəbəkələri',
    teacher: 'Ceyhun Əlizadə',
    room: '306',
    type: 'məş',
    subgroup: 'hamisi',
    week: 'alt',
  },
];